### ISSUE TITLE
Agent in Excel/GeoJSON files doesn't work

### ISSUE THREAD

**Issue by davidvlaminck** [davidvlaminck/OTLMOW-Converter#25]

**Comment by VerdoodtDries** [comment]
[Uploading cannot_export_Agent.txt…]()

**Comment by VerdoodtDries** [comment]
`
DEBUG:root:called
DEBUG:root:Closing connection to subset database
DEBUG:root:Saving project to C:\Users\chris\OTLWizardProjects\Projects\simpele_vergelijkings_project_data_2
ERROR:root:error caught!
ERROR:root:error message: 
: Traceback (most recent call last):
  File "C:\Users\chris\PycharmProjects\OTLMOW-GUI\GUI\Screens\ExportDataScreen.py", line 78, in <lambda>
    self.export_btn.clicked.connect(lambda: self.open_file_picker())
                                            ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\chris\PycharmProjects\OTLMOW-GUI\GUI\Screens\ExportDataScreen.py", line 122, in open_file_picker
    ExportDataDomain.generate_files(document_loc[0], global_vars.current_project, csv_option, split_relations_and_objects)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\PycharmProjects\OTLMOW-GUI\Domain\ExportDataDomain.py", line 56, in generate_files
    OtlmowConverter.from_objects_to_file(file_path=Path(end_file),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
                                         sequence_of_objects=objects_in_memory,
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                         abbreviate_excel_sheettitles=True )
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\PycharmProjects\OTLMOW-GUI\venv_py3-13\Lib\site-packages\otlmow_converter\OtlmowConverter.py", line 285, in from_objects_to_file
    exporter.from_objects(sequence_of_objects=sequence_of_objects, filepath=file_path, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chris\PycharmProjects\OTLMOW-GUI\venv_py3-13\Lib\site-packages\otlmow_converter\FileFormats\ExcelExporter.py", line 40, in from_objects
    table_dict = DotnotationTableConverter.get_tables_per_type_from_data(
        cardinality_separator=cardinality_separator, cardinality_indicator=cardinality_indicator,
    ...<2 lines>...
        warn_for_non_otl_conform_attributes=warn_for_non_otl_conform_attributes,
        sequence_of_objects=sequence_of_objects, values_as_string=True)
  File "C:\Users\chris\PycharmProjects\OTLMOW-GUI\venv_py3-13\Lib\site-packages\otlmow_converter\FileFormats\DotnotationTableConverter.py", line 113, in get_tables_per_type_from_data
    short_uri = get_shortened_uri(otl_object.typeURI)
  File "C:\Users\chris\PycharmProjects\OTLMOW-GUI\venv_py3-13\Lib\site-packages\otlmow_model\OtlmowModel\Helpers\GenericHelper.py", line 10, in get_shortened_uri
    raise ValueError(f'{object_uri} is not a valid uri to extract a namespace from')
ValueError: http://purl.org/dc/terms/Agent is not a valid uri to extract a namespace from
`

**Comment by christiaan20** [comment]
This error occurs because the get_shortened_uri function in [GenericHelper]( https://github.com/davidvlaminck/OTLMOW-Model/blob/master/otlmow_model/OtlmowModel/Helpers/GenericHelper.py) looks for the string '/ns/' that is in all other typeURIs but not in the unique typeURI of Agent which is http://purl.org/dc/terms/Agent.

This specific error would be solved if the get_shortened_uri function also check for http://purl.org/dc/terms/ to account for the Agent object. I don't know if there would be more problems down the road though.
